apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-pr-binding
spec:
  params:
    - name: githubcloneurl
      value: $(body.repository.clone_url)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: github-template
spec:
  params:
    - name: githubcloneurl # Here we reference the parameters defined in our TriggerBinding
  resourcetemplates: # This defines the template that should be used to create a resource when an event arrives
    - apiVersion: tekton.dev/v1beta1
      kind: TaskRun
      metadata:
        generateName: github-hello-run-
      spec:
        taskRef:
          name: hello # Referencing our previously created task again
        params:
          - name: recipient
            value: $(tt.params.githubcloneurl) # using `tt` we can reference the parameters of the TriggerTemplate
---
apiVersion: v1
kind: Secret
metadata:
  name: github-secret # the github interceptor needs a secret containing the key to verify the payload
type: Opaque
stringData:
  secretToken: "1234567"
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-listener
spec:
  triggers:
    - name: github-listener
      interceptors: # interceptors run after receiving an event but before running the TriggerBinding, they can do some extra filtering and validations
        - ref:
            name: "github" # The GitHub interceptor is a provided interceptor that validates the payload signature and can do some filtering like only certain event types
          params:
            - name: "secretRef"
              value:
                secretName: github-secret # above secret with the key for payload verification
                secretKey: secretToken
            - name: "eventTypes" # filtering on event types
              value: ["pull_request"]
        - name: "only when PRs are opened"
          ref:
            name: "cel" # CEL is an expression language that can be used for additional filtering
          params:
            - name: "filter"
              value: "body.action in ['opened', 'synchronize', 'reopened']"
      bindings:
        - ref: github-pr-binding # reference our TriggerBinding
      template:
        ref: github-template # and reference our TriggerTemplate
