apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: hello-task-run
spec:
  taskRef:
    name: hello # we reference the task we have just created
  params:
    - name: recipient
      value: "Patrick" # and pass in our parameters
